[package]
name = "share_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.40.2", features = ["bundled", "blob"] }
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
futures-util = "0.3.34"
rand = "0.10.2"
base64 = "0.23.1"
tokio-util = { version = "0.7.19", features = ["io"] }